// Generated by psc-bundle 0.11.6
var PS = {};
(function(exports) {
    "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Console"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Show = PS["Data.Show"];
  var Data_Unit = PS["Data.Unit"];
  exports["log"] = $foreign.log;
})(PS["Control.Monad.Eff.Console"] = PS["Control.Monad.Eff.Console"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  exports.select = function(selector) {
      return function() {
          return jQuery(selector);
      };
  };

  exports.create = function(html) {
      return function() {
          return jQuery(html);
      };
  };

  exports.setAttr = function(attr) {
      return function(val) {
          return function(ob) {
              return function() {
                  ob.attr(attr, val);
              };
          };
      };
  };

  exports.attr = function(attrs) {
      return function(ob) {
          return function() {
              ob.attr(attrs);
          };
      };
  };

  exports.css = function(props) {
      return function(ob) {
          return function() {
              ob.css(props);
          };
      };
  };

  exports.toggleClass = function(cls) {
      return function(ob) {
          return function() {
              ob.toggleClass(cls);
          };
      };
  };

  exports.setClass = function(cls) {
      return function(flag) {
          return function(ob) {
              return function() {
                  ob.toggleClass(cls, flag);
              };
          };
      };
  };

  exports.append = function(ob1) {
      return function(ob) {
          return function() {
              ob.append(ob1);
          };
      };
  };

  exports.appendText = function(s) {
      return function(ob) {
          return function() {
              ob.append(s);
          };
      };
  };

  exports.body = function() {
      return jQuery(document.body);
  };

  exports.on = function(evt) {
      return function(act) {
          return function(ob) {
              return function() {
                  ob.on(evt, function(e) {
                      act(e)(jQuery(this))();
                  });
              };
          };
      };
  };
})(PS["Control.Monad.Eff.JQuery"] = PS["Control.Monad.Eff.JQuery"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var $foreign = PS["Control.Monad.Eff.JQuery"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var Data_Foreign = PS["Data.Foreign"];
  var Data_Functor = PS["Data.Functor"];
  var Data_Maybe = PS["Data.Maybe"];
  var Prelude = PS["Prelude"];            
  var addClass = function (cls) {
      return $foreign.setClass(cls)(true);
  };
  exports["addClass"] = addClass;
  exports["append"] = $foreign.append;
  exports["appendText"] = $foreign.appendText;
  exports["body"] = $foreign.body;
  exports["create"] = $foreign.create;
  exports["css"] = $foreign.css;
  exports["on"] = $foreign.on;
  exports["select"] = $foreign.select;
  exports["setAttr"] = $foreign.setAttr;
})(PS["Control.Monad.Eff.JQuery"] = PS["Control.Monad.Eff.JQuery"] || {});
(function(exports) {
  // Generated by purs version 0.11.6
  "use strict";
  var Control_Bind = PS["Control.Bind"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Control_Monad_Eff_JQuery = PS["Control.Monad.Eff.JQuery"];
  var DOM = PS["DOM"];
  var Partial_Unsafe = PS["Partial.Unsafe"];
  var Prelude = PS["Prelude"];        
  var dragEvent = function (main1) {
      return function (cube) {
          return function (v) {
              return function (v1) {
                  return function __do() {
                      var v2 = Control_Monad_Eff_JQuery.select(".cube")();
                      return Control_Monad_Eff_JQuery.css({
                          animation: "rotate 5s linear infinite", 
                          transitionDuration: "3s"
                      })(v2)();
                  };
              };
          };
      };
  };
  var render3DCube = function __do() {
      var v = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("front")(v)();
      Control_Monad_Eff_JQuery.addClass("face")(v)();
      Control_Monad_Eff_JQuery.appendText("J ")(v)();
      var v1 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("back")(v1)();
      Control_Monad_Eff_JQuery.addClass("face")(v1)();
      Control_Monad_Eff_JQuery.appendText("U ")(v1)();
      var v2 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("right")(v2)();
      Control_Monad_Eff_JQuery.addClass("face")(v2)();
      Control_Monad_Eff_JQuery.appendText("S ")(v2)();
      var v3 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("left")(v3)();
      Control_Monad_Eff_JQuery.addClass("face")(v3)();
      Control_Monad_Eff_JQuery.appendText("P ")(v3)();
      var v4 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("top")(v4)();
      Control_Monad_Eff_JQuery.addClass("face")(v4)();
      Control_Monad_Eff_JQuery.appendText("A ")(v4)();
      var v5 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("bottom")(v5)();
      Control_Monad_Eff_JQuery.addClass("face")(v5)();
      Control_Monad_Eff_JQuery.appendText("Y ")(v5)();
      var v6 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.addClass("cube")(v6)();
      Control_Monad_Eff_JQuery.css({
          transform: "translateZ(100px)", 
          backgroundColor: "red"
      })(v)();
      Control_Monad_Eff_JQuery.css({
          transform: "rotateY(180deg) translateZ(100px)", 
          backgroundColor: "green"
      })(v1)();
      Control_Monad_Eff_JQuery.css({
          transform: "rotateY(-270deg) translateX(100px)", 
          transformOrigin: "top right", 
          backgroundColor: "blue"
      })(v2)();
      Control_Monad_Eff_JQuery.css({
          transform: "rotateY(270deg) translateX(-100px)", 
          transformOrigin: "center left", 
          backgroundColor: "cyan"
      })(v3)();
      Control_Monad_Eff_JQuery.css({
          transform: "rotateX(-90deg) translateY(-100px)", 
          transformOrigin: "top center", 
          backgroundColor: "magenta"
      })(v4)();
      Control_Monad_Eff_JQuery.css({
          transform: "rotateX(90deg) translateY(100px)", 
          transformOrigin: "bottom center", 
          backgroundColor: "yellow"
      })(v5)();
      Control_Monad_Eff_JQuery.css({
          position: "relative", 
          transformStyle: "preserve-3d"
      })(v6)();
      Control_Monad_Eff_JQuery.append(v)(v6)();
      Control_Monad_Eff_JQuery.append(v1)(v6)();
      Control_Monad_Eff_JQuery.append(v2)(v6)();
      Control_Monad_Eff_JQuery.append(v3)(v6)();
      Control_Monad_Eff_JQuery.append(v4)(v6)();
      Control_Monad_Eff_JQuery.append(v5)(v6)();
      var v7 = Control_Monad_Eff_JQuery.create("<div>")();
      Control_Monad_Eff_JQuery.setAttr("id")("main")(v7)();
      Control_Monad_Eff_JQuery.addClass("main")(v7)();
      Control_Monad_Eff_JQuery.css({
          position: "absolute", 
          left: "50%", 
          top: "50%", 
          perspective: "1500px"
      })(v7)();
      Control_Monad_Eff_JQuery.append(v6)(v7)();
      var v8 = Control_Monad_Eff_JQuery.body();
      Control_Monad_Eff_JQuery.addClass("body")(v8)();
      Control_Monad_Eff_JQuery.css({
          overflow: "hidden"
      })(v8)();
      Control_Monad_Eff_JQuery.append(v7)(v8)();
      Control_Monad_Eff_JQuery.css({
          width: "100%", 
          height: "100%"
      })(v8)();
      var v9 = Control_Monad_Eff_JQuery.select(".face")();
      Control_Monad_Eff_JQuery.css({
          position: "absolute", 
          width: "200px", 
          height: "200px", 
          border: "solid black 5px"
      })(v9)();
      Control_Monad_Eff_JQuery.css({
          transform: "rotateX(-45deg)rotateY(45deg)"
      })(v6)();
      return Control_Monad_Eff_JQuery.on("mouseover")(dragEvent(v7)(v6))(v7)();
  };
  var main = function __do() {
      render3DCube();
      return Control_Monad_Eff_Console.log("done")();
  };
  exports["dragEvent"] = dragEvent;
  exports["main"] = main;
  exports["render3DCube"] = render3DCube;
})(PS["Main"] = PS["Main"] || {});
PS["Main"].main();
